name: Invisible Guest Automation
 
on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 */2 * *"
jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

   
          pip install pandas openpyxl psycopg2-binary

      - name: Run automation script
        run: python ig_automation.py

      - name: Install dependencies
        run: |
        pip install pandas numpy openpyxl psycopg2-binary word2number
